version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"               # Enables the dashboard (development only)
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"                         # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
    networks:
      - web

  api:
    build: ./api
    container_name: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      # Basic Auth middleware for API (user: admin, password: password)
      - "traefik.http.routers.api.middlewares=api-basic-auth"
      - "traefik.http.middlewares.api-basic-auth.basicauth.users=admin:$$2a$$12$$yLbDJIc3rkpRKLCR1WBUH.q2ZCaRCRfDDdejPLlz/ZkXJkctk/5Tm"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
